Nab 438
nablarch/nablarch-mail-sender pull request #23
Opened 2022-01-06 11:36 UTC by fyamvbf

2022-01-07 05:44 UTC, kumagoro1202 requested changes

2022-01-07 05:44 UTC, kumagoro1202 commented on src/main/java/nablarch/common/mail/MailRequestTable.java
> +                        statement.setString(paramPosition++, mailSendPatternId);
ここで後置のインクリメント演算子入れてますが使われることがなく無駄です。
また、paramPositionをインクリメントで計算していますが、可変な条件は一個しかないのでわざわざ変数にせず他と同様1、2、3とintで書けばいいです。
https://github.com/nablarch/nablarch-mail-sender/blob/master/src/main/java/nablarch/common/mail/MailRequestTable.java#L300
これを参考にしたんだと思いますが、これは可変条件が2個あって場合によってparamPositionが2になるか3になるかが実行時まで判定できないから特別にやってます。他は全部intで直接指定しているので合わせてください。

2022-01-07 05:44 UTC, kumagoro1202 commented on src/test/java/nablarch/common/mail/MailSenderMultiProcessTest.java
> +     * ダミーのプロセスIDが付与されたものは処理されないことも検証する。<br>
パターンごとに2回やる意味はないです。
元のテストで抜けていたのは対象外のパターンのレコードのプロセスIDが更新されていないことのassertだけです。

2022-01-11 02:41 UTC, fyamvbf commented on src/main/java/nablarch/common/mail/MailRequestTable.java
> +                        statement.setString(paramPosition++, mailSendPatternId);
対応しました　https://github.com/nablarch/nablarch-mail-sender/pull/23/commits/a4f2cd376b59ca6e1605f2de0525c40ed7e0c9ba

2022-01-11 02:42 UTC, fyamvbf commented on src/test/java/nablarch/common/mail/MailSenderMultiProcessTest.java
> +     * ダミーのプロセスIDが付与されたものは処理されないことも検証する。<br>
冗長になっていた２回目を削除しました。　https://github.com/nablarch/nablarch-mail-sender/pull/23/commits/5e21fc0710d7a465ccee76b5ead22db806ff56b5

2022-01-11 02:58 UTC, kumagoro1202 requested changes

2022-01-11 02:58 UTC, kumagoro1202 commented on src/main/java/nablarch/common/mail/MailRequestTable.java
> +                    if (StringUtil.hasValue(mailSendPatternId)) {
ここの条件はmailSendPatternIdではなくmailSendPatternIdColumnNameの設定有無で判定するべきです。
mailSendPatternIdColumnNameが設定されているのにmailSendPatternIdを引数で渡してこない場合は以下同様に例外を投げるべきです。そうしないとmailSendPatternIdColumnNameを間違えて設定した場合になぜ空振るかの原因究明が難しくなります。
https://github.com/nablarch/nablarch-mail-sender/blob/master/src/main/java/nablarch/common/mail/MailRequestTable.java#L305-L311

2022-01-11 02:58 UTC, kumagoro1202 commented on src/test/java/nablarch/common/mail/MailSenderMultiProcessTest.java
> +        String mailRequestId1 = "1";
今回の修正で必要のある修正ではないはずです。
修正量が無駄に多くなってどういう意図で改修が必要だったかがわからなくなります。
コメント含めて意図がない変更は元にもどしてください。
プロセスIDのassert以外は雑音になっています。

2022-01-11 05:25 UTC, fyamvbf commented on src/test/java/nablarch/common/mail/MailSenderMultiProcessTest.java
> +        String mailRequestId1 = "1";
修正しました　https://github.com/nablarch/nablarch-mail-sender/pull/23/commits/0eb0407fe28dd07c5bb987d6a3b2aa5342271afa

2022-01-11 05:34 UTC, kumagoro1202 requested changes

2022-01-11 05:34 UTC, kumagoro1202 commented on src/test/java/nablarch/common/mail/MailSenderMultiProcessTest.java
> +        // 処理対象となるmailRequestId1はプロセスIDが更新され、それ以外は変わっていないことを確認
DBの検証はL340以降でまとめてやっています。他のテストメソッドもまとめてやっているので合わせてください。

2022-01-11 05:55 UTC, kumagoro1202 requested changes

2022-01-11 05:55 UTC, kumagoro1202 commented on src/test/java/nablarch/common/mail/MailSenderMultiProcessTest.java
> +        String dummyProcessID = UUID.randomUUID().toString();
他のテストメソッドではotherProcessId になってます。明確な意図がないなら合わせてください。
https://github.com/nablarch/nablarch-mail-sender/blob/master/src/test/java/nablarch/common/mail/MailSenderMultiProcessTest.java#L210

2022-01-11 07:31 UTC, kumagoro1202 commented on src/main/java/nablarch/common/mail/MailRequestTable.java
> +                    if (StringUtil.hasValue(mailSendPatternId)) {
mailSendPatternIdが設定されていない場合、呼び出し元でここに到達する前にエラーとなるためこの指摘は取り下げ

2022-01-11 08:00 UTC, fyamvbf commented on src/test/java/nablarch/common/mail/MailSenderMultiProcessTest.java
> +        // 処理対象となるmailRequestId1はプロセスIDが更新され、それ以外は変わっていないことを確認
DB処理を末尾に移動　https://github.com/nablarch/nablarch-mail-sender/pull/23/commits/beb44063e7b264c5da170b93a0d809ff32429220

2022-01-11 08:01 UTC, fyamvbf commented on src/test/java/nablarch/common/mail/MailSenderMultiProcessTest.java
> +        String dummyProcessID = UUID.randomUUID().toString();
変数名を変更　https://github.com/nablarch/nablarch-mail-sender/pull/23/commits/beb44063e7b264c5da170b93a0d809ff32429220

2022-01-11 08:07 UTC, kumagoro1202 requested changes

2022-01-11 08:07 UTC, kumagoro1202 commented on src/test/java/nablarch/common/mail/MailSenderMultiProcessTest.java
> +		String nonTargetMailSendPatternId = "01";
インデントがタブになっています。

2022-01-11 08:07 UTC, kumagoro1202 commented on src/test/java/nablarch/common/mail/MailSenderMultiProcessTest.java
> +		VariousDbTestHelper.setUpTable(
インデントがタブ

2022-01-11 08:07 UTC, kumagoro1202 commented on src/test/java/nablarch/common/mail/MailSenderMultiProcessTest.java
> +                        SystemTimeUtil.getTimestamp(), null, mailBody, targetMailSendPatternId, otherProcessId));
見比べにくいので改行位置そろえて欲しいです。
```
                new MailRequestPatternMultiProcess(mailRequestId1, subject, from, replyTo, returnPath, charset,
                        mailConfig.getStatusUnsent(), SystemTimeUtil.getTimestamp(), null, mailBody, targetMailSendPatternId, null),
                new MailRequestPatternMultiProcess(mailRequestId2, subject, from, replyTo, returnPath, charset, mailConfig.getStatusUnsent(),
                        SystemTimeUtil.getTimestamp(), null, mailBody, nonTargetMailSendPatternId, null),
                new MailRequestPatternMultiProcess(mailRequestId3, subject, from, replyTo, returnPath, charset, mailConfig.getStatusUnsent(),
                        SystemTimeUtil.getTimestamp(), null, mailBody, targetMailSendPatternId, otherProcessId));
```
↓
```
                new MailRequestPatternMultiProcess(mailRequestId1, subject, from, replyTo, returnPath, charset,
                        mailConfig.getStatusUnsent(), SystemTimeUtil.getTimestamp(), null, mailBody, targetMailSendPatternId, null),
                new MailRequestPatternMultiProcess(mailRequestId2, subject, from, replyTo, returnPath, charset,
                        mailConfig.getStatusUnsent(), SystemTimeUtil.getTimestamp(), null, mailBody, nonTargetMailSendPatternId, null),
                new MailRequestPatternMultiProcess(mailRequestId3, subject, from, replyTo, returnPath, charset,
                        mailConfig.getStatusUnsent(), SystemTimeUtil.getTimestamp(), null, mailBody, targetMailSendPatternId, otherProcessId));
```

2022-01-11 08:12 UTC, fyamvbf commented on src/test/java/nablarch/common/mail/MailSenderMultiProcessTest.java
> +                        SystemTimeUtil.getTimestamp(), null, mailBody, targetMailSendPatternId, otherProcessId));
修正しました　https://github.com/nablarch/nablarch-mail-sender/pull/23/commits/2bf13df0d722d9d8eb252d006f46b9e695d80c9d

2022-01-11 08:16 UTC, fyamvbf commented on src/test/java/nablarch/common/mail/MailSenderMultiProcessTest.java
> +		String nonTargetMailSendPatternId = "01";
修正しました　https://github.com/nablarch/nablarch-mail-sender/pull/23/commits/6a226f0b107e01a67cd25ffa524fafee721275e5

2022-01-11 08:16 UTC, fyamvbf commented on src/test/java/nablarch/common/mail/MailSenderMultiProcessTest.java
> +		VariousDbTestHelper.setUpTable(
修正しました　https://github.com/nablarch/nablarch-mail-sender/pull/23/commits/6a226f0b107e01a67cd25ffa524fafee721275e5

2022-01-11 08:24 UTC, kumagoro1202 approved these changes

2022-01-11 08:24 UTC, merged